export const ACTION_TYPE = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
  SET_PRODUCTS: "SET_PRODUCTS",
  CLOSE_MODAL: "CLOSE_MODAL",
  ON_OPEN_MODAL: "ON_OPEN_MODAL",
  RESET_POST_DATA: "RESET_POST_DATA",
  ADD_PRODUCT_IN_CARD: "ADD_PRODUCT_IN_CARD",
  REMOVE_PRODUCT_FROM_CARD: "REMOVE_PRODUCT_FROM_CARD",
};
